export const products = [
    {
      id: 4,
      name: "Sate",
      category: "Makanan Tradisional",
      price: 1.2,
      image: "/images/sate1.jpg",
      isCart: false,
      description:"Sate ayam yang juicy dan enak.",
    },
    {
      id: 5,
      name: "Semur Jengkol",
      category: "Makanan Tradisional",
      price: 3.17,
      image: "/images/semurjengkol12.jpg",
      isCart: false,
      description: "Bau?Oh tentu tidak!Jengkol ini diolah dengan sangat baik!",
    },
    {
      id: 6,
      name: "Pempek",
      category: "Makanan Tradisional",
      price: 2.69,
      image: "/images/pempek8.jpg",
      isCart: false,
      description:"Pempek dengan beragam isian dan bentuk.Pasti membuatmu jatuh hati!",
    },
    {
      id: 7,
      name: "Ayam Penyet",
      category: "Makanan Tradisional",
      price: 6.30 ,
      image: "/images/ayampenyet4.jpg",
      isCart: false,
      description:"Ayam ini dimasak dengan khas dengan bumbu kuning.",
    },
    {
      id: 8,
      name: "Martabak Manis",
      category: "Makanan Modern",
      price: 6.30,
      image: "/images/martabak3.jpg",
      isCart: false,
      description:"Martabak manis dengan taburan cokelat dan keju.",
    },
    {
      id: 9,
      name: "Martabak Asin",
      category: "Makanan Modern",
      price: 6.30 ,
      image: "/images/martabakasin9.jpg",
      isCart: false,
      description:"Martabak asin yang dibuat dengan telur dan bahan-bahan lain yang berkualitas.",
    },
    {
      id: 10,
      name: "Cupcake",
      category: "Makanan Modern",
      price: 6.30 ,
      image: "/images/cupcake.jpg",
      isCart: false,
      description:"Cupcake ini dibuat dengan bahan-bahan prempium.",
    },
    {
      id: 11,
      name: "Puding",
      category: "Makanan Modern",
      price: 6.30 ,
      image: "/images/puding.jpeg",
      isCart: false,
      description:"Dibuat dengan susu sapi dan perisa buah murni yang berkualitas premium.",
    },
  ];