export const products = [
    {
      id: 1,
      name: "Jam Tangan warna hitam,elegan,dan menarik.",
      category: "Jam Tangan",
      price: 4.78,
      image: "/images/produk1.jpg",
      isCart: false,
      description:"Jam tangan elegan yang membuat anda akan selalu mengingat waktu.Cocok dengan lingkar tangan berapapun karena dapat dikencangkan dan dikendorkan dengan custom. ",
    },
    {
      id: 2,
      name: "Tas pink yang cocok untuk sekolah dan bermain",
      category: "Tas",
      price: 3.17,
      image: "/images/produk2.jpg",
      isCart: false,
      description: "Tas pink ini bervolume  besar sehingga muat untuk banyak barang termasuk laptop dan peralatan sekolah. ",
    },
    {
      id: 3,
      name: "Sepatu converse ini sangat nyaman untuk anda pakai kemanapun,kapanpun,dan dimanapun.Ukuran kaki dari 42-50",
      category: "Sepatu",
      price: 2.69,
      image: "/images/produk3.jpg",
      isCart: false,
      description:"Berwarna hitam dan putih yang membuat sepatu ini sangat elegan dan cocok untuk anda.",
    },
    {
      id: 4,
      name: "Buku Tulis dengan ilustrasi kartun yang sangat kawai atau lucu",
      category: "Buku Tulis",
      price: 6.30 ,
      image: "/images/produk8.jpg",
      isCart: false,
      description:"Buku tulis ini membantu anda menulis segala ilmu pengetahuan di dunia ini.",
    },
    {
      id: 5,
      name: "Pensil hitam yang sangat kokoh.",
      category: "Pensil",
      price: 6.30,
      image: "/images/produk9.jpg",
      isCart: false,
      description:"Pensil dengan warna hitam ini sangat nyaman untuk anda pakai menulis.Bagian dalamnya sangat kuat dan tahan banting.",
    },
    {
      id: 6,
      name: "Tempat Pensil yang cocok untuk anak-anak",
      category: "Tempat Pensil",
      price: 6.30 ,
      image: "/images/produk10.jpg",
      isCart: false,
      description:"Tempat pensil atau box ini memungkinkan anda membawa banyak barang seperti pensil,penggaris,dan penghapus.",
    },
    {
      id: 7,
      name: "Seragam mulai dari SD,SMP,& SMA",
      category: "Seragam",
      price: 6.30 ,
      image: "/images/produk11.jpg",
      isCart: false,
      description:"Seragam ini terbuat dari kain yang nyaman dipakai,halus,dan berkualitas premium.Tidak akan gerah sekalipun dipakai di tempat panas.",
    },
    {
      id: 8,
      name: "Kaus Kaki warna-warni yang cocok untuk anda pakai kemanapun.",
      category: "Kaus Kaki",
      price: 6.30 ,
      image: "/images/produk12.jpeg",
      isCart: false,
      description:"Kaus Kaki yang cocok anda pakai untuk bertamasya dengan keluarga atau hang-out dengan teman-teman.",
    },
  ];